modLoader="javafml"
loaderVersion="[40,)"
license="MIT"


[[mods]] #mandatory

modId="destinymod"
version="${file.jarVersion}"
displayName="Destiny 2 Mod"

# logoFile="examplemod.png"

credits="Thanks for this example mod goes to Java"
authors="TaeliaDieaux"
description='''
A mod that aims to allow the player to play Destiny inside Minecraft !
'''


[[dependencies.destinymod]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.destinymod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"